/**
 * 수파베이스 테이블 생성 방법
 * 
 * 1. Supabase 대시보드(https://app.supabase.com)에 로그인합니다.
 * 2. 프로젝트를 선택합니다.
 * 3. 왼쪽 메뉴에서 "SQL Editor"를 클릭합니다.
 * 4. "New Query"를 클릭합니다.
 * 5. 아래의 SQL을 복사하여 붙여넣습니다.
 * 6. "Run"을 클릭하여 실행합니다.
 */

export const vocabularyTableSetupSQL = `
-- 어휘 테이블
CREATE TABLE vocabulary (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  english TEXT NOT NULL,
  korean TEXT NOT NULL,
  favorite BOOLEAN DEFAULT FALSE,
  last_reviewed TIMESTAMP WITH TIME ZONE,
  review_count INTEGER DEFAULT 0
);

-- 공개 테이블 접근 정책
ALTER TABLE vocabulary ENABLE ROW LEVEL SECURITY;

-- 사용자는 자신의 단어만 볼 수 있음
CREATE POLICY "Users can view own vocabulary" 
  ON vocabulary FOR SELECT 
  USING (auth.uid() = user_id);

-- 사용자는 자신의 단어만 추가할 수 있음
CREATE POLICY "Users can insert own vocabulary" 
  ON vocabulary FOR INSERT 
  WITH CHECK (auth.uid() = user_id);

-- 사용자는 자신의 단어만 업데이트할 수 있음
CREATE POLICY "Users can update own vocabulary" 
  ON vocabulary FOR UPDATE 
  USING (auth.uid() = user_id);

-- 사용자는 자신의 단어만 삭제할 수 있음
CREATE POLICY "Users can delete own vocabulary" 
  ON vocabulary FOR DELETE 
  USING (auth.uid() = user_id);
`;

/**
 * 데이터베이스 문제 해결 안내
 * 
 * 이 함수는 단순히 Supabase에서 테이블을 생성하기 위한 SQL 문을 반환합니다.
 * "relation 'public.vocabulary' does not exist" 오류가 발생하면 이 SQL을 Supabase 대시보드에서 실행해야 합니다.
 */
export function getVocabularySetupInstructions() {
  return {
    error: 'vocabulary 테이블이 존재하지 않습니다.',
    solution: '수파베이스 대시보드의 SQL 에디터에서 다음 쿼리를 실행하세요:',
    sql: vocabularyTableSetupSQL
  };
} 