-- 어휘 테이블
CREATE TABLE IF NOT EXISTS vocabulary (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  english TEXT NOT NULL,
  korean TEXT NOT NULL,
  favorite BOOLEAN DEFAULT FALSE,
  last_reviewed TIMESTAMP WITH TIME ZONE,
  review_count INTEGER DEFAULT 0
);

-- 공개 테이블 접근 정책
ALTER TABLE vocabulary ENABLE ROW LEVEL SECURITY;

-- 사용자는 자신의 단어만 볼 수 있음
CREATE POLICY "Users can view own vocabulary" 
  ON vocabulary FOR SELECT 
  USING (auth.uid() = user_id);

-- 사용자는 자신의 단어만 추가할 수 있음
CREATE POLICY "Users can insert own vocabulary" 
  ON vocabulary FOR INSERT 
  WITH CHECK (auth.uid() = user_id);

-- 사용자는 자신의 단어만 업데이트할 수 있음
CREATE POLICY "Users can update own vocabulary" 
  ON vocabulary FOR UPDATE 
  USING (auth.uid() = user_id);

-- 사용자는 자신의 단어만 삭제할 수 있음
CREATE POLICY "Users can delete own vocabulary" 
  ON vocabulary FOR DELETE 
  USING (auth.uid() = user_id); 